### ISSUE TITLE
ニコニコ動画 nicovideo.jp で Adblock Plus の要素非表示フィルタが無効になってしまう

### ISSUE THREAD

**Issue by tofukko** [tofukko/filter#16]
### ■説明
Adblock Plus + 豆腐フィルタで[ニコニコ動画](https://www.nicovideo.jp/)を見ると
要素非表示フィルタやマイフィルターが働かなくなってしまう

### ■対策
どうも Adblock Plus は
`www.nicovideo.jp##.mb8p4:has( > #web_pc_prime)`
のようなuBO用の記法で書かれたフィルタがあると、そのサイトで要素非表示フィルタを全て無効にしてしまうようだ。

対策としては
1. Adblock Plus をサポート対象外とする
2. `www.nicovideo.jp#?#.mb8p4:-abp-has(> #web_pc_prime)`のようにABP記法に書き直す

まあ2しか無いかな
未だ Adblock Plus を使っている人も多いようだし

### ■ちなみに
`##.hogera:-abp-has( > .raripappa)`
こういう書き方（不等号直前のスペース）も駄目みたいで要素非表示が無効になる
正しくは
`##.hogera:-abp-has(> .raripappa)`

**Comment by Yuki2718** [comment]
差し出がましいかもしれませんが、おそらく`#?#:-abp-has()`に統一されるのがベストなのではないかと思います。主要なブロッカーのすべてに互換性があり、これ一つでuBOでもAGでも動作します。同様に`:has-text()`は`#?#:-abp-contains()`で対応できますが、`:upward()`はABPはサポートしないのであきらめてもらうか、前の二つで書き直すかになります。()内の評価はJavascriptで行っていることもあり結構敏感で、後ろにも余分なスペースは入れられません（`https://github.com/eEIi0A5L/adblock_filter/commit/4b7da1f653dcdca0c6a40b4abe54e9d4f49a29ce#commitcomment-44609799`）。

ちなみに、`##+js(aopr, hoge)`, `##+js(aopw, hoge)`, `##+js(acis, hoge, hoge2)`, `##+js(set, hoge)`, `##+js(json-prune, hoge)`あたりはABPも対応していますがお互いに文法互換性がなく、対応するとしたら両方書く必要があります。対応は順番に
```
#$#abort-on-property-read hoge
#$#abort-on-property-write hoge
#$#abort-current-inline-script hoge hoge2
#$#override-property-read hoge
#$#json-prune hoge

```
です。nowoifなどサポートされていないものは、`:style()`や`:remove()`もですが、あきらめてもらうしかないかと・・

**Comment by tofukko** [comment]
そうですね。全て-abp-hasと-abp-containsにしてしまおうと思います。
##+js～に関しては、それで困る人はいずれuBOにたどり着くだろうという希望的観測から放置することにしました。

**Comment by tofukko** [comment]
Adblock Plus + 豆腐フィルタで広告が消えていること、マイフィルターが効いている事を確認
