### ISSUE TITLE
デッドドメインの報告

### ISSUE THREAD

**Issue by Yuki2718** [tofukko/filter#3]
もしブログでの報告をお好みでしたらすみません、その場合次からはそういたします。
リクエストというより情報提供ですが、豆腐フィルタに含まれているデッドドメイン（完全に死んでいるもののみ）のリストです。対応は作者さんによって違うようなので、お任せします。

```
ad1-click.com
adimg.net
b.grvcdn.com
clcount.com (非表示ルール)
cyberwing.co.jp
iogous.com
japanmetrix.jp
next-channel.com
lead-ad.jp
media-rep.com
nex8.net
owldata.com
rdp.pro.ne.jp
tacoda.net
trax-ad.jp
unthem.com
user.in.net
```

あと、
`ashemaletube.com##+js(set, popunder, noopFunc)`
は不要です
`https://github.com/uBlockOrigin/uAssets/issues/7704`

**Comment by tofukko** [comment]
ありがとうとても助かります
書くのはどこでもいいですよ

**Comment by Yuki2718** [comment]
そう言っていただけるとよかったです。
今後も気づいたことがありましたら報告させていただきます。
