### ISSUE TITLE
mixch.tv 動画が再生できない

### ISSUE THREAD

**Issue by ghost** [tofukko/filter#33]
### ■URL
`https://mixch.tv/`

### ■説明
ライブ配信サイトで動画が全く再生できない。

### ■スクリーンショット

<details><summary>Screenshot 1</summary>

![Screenshot 1](https://user-images.githubusercontent.com/82331005/122059069-38fbbb00-ce27-11eb-9319-caaf2db15c55.png)
</details>

<details><summary>Screenshot 2</summary>

![Screenshot 2](https://user-images.githubusercontent.com/82331005/122059064-3731f780-ce27-11eb-826f-593c4ebb45f0.png)
</details>

#### 原因フィルタ
`-analytics.js$domain=~www.apple.com|~youtube.com`
#### ブロックされたURL
`https://www.gstatic.com/firebasejs/8.6.3/firebase-analytics.js`

**Comment by tofukko** [comment]
ひとまずホワイトリストで対応しますが、`-analytics.js$domain=~www.apple.com|~youtube.com`がちょっと雑なので削除予定に入れておきます
