### ISSUE TITLE
汎用非表示の提案

### ISSUE THREAD

**Issue by Yuki2718** [tofukko/filter#4]
削除された汎用非表示の埋め合わせとして、これは入れていいだろうというものを適当にピックしてみました。コメントとしてそれが有効なサイトをいくつか入れました。
```
! blog.ss-blog.jp,bnewg.sokuho.org,majimanjisokuhou.com,scienceplus2ch.com
###overlay-ad-div-id

141tube.com,japanhub.net 他、多くのアダルトサイト
##.ad-body

! www.morningstar.co.jp 他、多くのwordpressブログ
! 入れる場合、seiga.nicovideo.jp##.ad_areaが不要になるかも
##.ad_area

! baseball.antenam.info,ffbe.atna.jp,mgmaster.antenam.info,monhan-world.antenam.jp
##.ad_footer

! kakaku.com,syosetu.com 他、多くの学術雑誌系
##.c-ad
```

**Comment by Yuki2718** [comment]
すみません、Wordpressでよく見るのは
`##.ad-area`の方でした
どちらも広範に使われているので両方入れてよいとは思いますが…

**Comment by tofukko** [comment]
ありがとうございます
全部入れることにしました

**Comment by Yuki2718** [comment]
追加です。`##.ad-area`にはおよびませんが、かなり一般的にみられるものです。
```
! expnote.com,socius101.com等、多くのWordpressブログ
##.ad-space
```
ほかにWordpressでよくみられるものとして、
```
##.adWidget
##.ad_widget
##.quads-location
```
等がありますが、コメントをだいぶ前に削除してしまいすぐには実例がみつかりませんでした。

**Comment by Yuki2718** [comment]
`##.quads-location`
は実例見つけました
`startupsns.com`

> むしろなぜpopinwokesanainoka?

popinは従来的なレコメンド以外にも色々手を出していて、少なくともドメイン丸ごとブロックすると問題が起きます。
もちフィルタさんに報告させていただいたこちらが一例です。
`https://jbbs.shitaraba.net/bbs/read.cgi/internet/24461/1510462016/226`
280さんのように
`||popin.cc/searchbox`
とすることでこの手の不具合はかなり軽減されますが、280さんもniftyを除外されているように完璧ではありません。私もだいぶ前にテレ朝系列で不具合を経験した記憶があります（上記のルールだと若干トラッカーが漏れるため、||r.popin.cc^も追加されています。niftyの例外がまだ必要かはわかりません）。

正直このあたりは私も悩んでいるのですが、不具合以外に考えられる理由の一つは広告部分がブロックできるかではないでしょうか。popinやgacraftは広告部分のみのブロックが簡単にできるため私は通しており、逆にloglyやcxense、忍者レコメンドはそれができない/難しいためブロックしてます（cxenseはたまに不具合起こしますが）。

ただ最近、じゃあRtoasterはどうなんだと…まだちゃんと確認してませんが、どうやらここの広告は別ドメイン（c-ovn.jp）から配信されるらしく、もしそうなら広告部分のブロックはできることに。しかもこれ、結構誤爆多いです。正直、外していい気もするんですがレコメンド系の非表示ルールを見直すのがめんどい…

**Comment by tofukko** [comment]
ありがとう.ad-space 以外はもう少し考えます

そういえば10年ぐらい前フィルタを公開してすぐの頃にpopinについて指摘された事があったようななかったようなことを思い出しました。レコメンド系は厄介ですね。
