### ISSUE TITLE
sankei.com uBO v1.36.x でリンクをクリックしても反応がない

### ISSUE THREAD

**Issue by ghost** [tofukko/filter#40]
https://github.com/uBlockOrigin/uAssets/issues/9505

v1.36系で大きく変更された`google-analytics_analytics.js`に問題があるのかもしれません。EPのGTM許可サイトをざっくりと確認しましたが、軽微ですがいくつかのサイトで不具合が復活していました。

**Comment by tofukko** [comment]
https://blog.hatenablog.com/
この辺りも同じ問題ががが

**Comment by tofukko** [comment]
https://www.sanspo.com/
https://www.iza.ne.jp/
http://www.sankeibiz.jp/
https://cachette.pet/
あああああああああああああああああああああああああああああああああああああああああ
