### ISSUE TITLE
豆腐フィルターを追加して搭載できる拡張機能について

### ISSUE THREAD

**Issue by takuyatahata** [tofukko/filter#88]
はじめまして、ブログとISSUEのどちらが都合が良いのかわかりませんがこちらで書き込みます。
晋遊舎の雑誌で知りました。
chatgptに質問して、どの拡張機能に入れられるか回答してもらいました。
googleの同期機能を使っていれば、次の機会にもあらかじめ入った状態で使えると思いますが、沢山他の拡張機能を入れていると失敗して、外れてしまっていると思います。
どのサイトに訪問したのか忘れたのですが、クラッシュしたことがありまして、その時に外れたのかもしれません。
スクリーンショットを証拠として取れませんでしたので、文章だけで書きました。
![コメント 2023-07-18 121914](https://github.com/tofukko/filter/assets/41463834/a3382b8e-8d01-40d8-a4c3-18f1d833e603)
ブログの方でもコメントしてもよろしいでしょうか？お忙しいとは思いますが、返信があるとありがたいです。

**Comment by tofukko** [comment]
何言ってるのかわからないので勘で答えてみます
豆腐フィルタを完全な形で使えるのは uBlock Origin だけです

**Comment by takuyatahata** [comment]
@tofukko 
わかりました。返信ありがとうございました。

**Comment by takuyatahata** [comment]
@tofukko さんへ
uBlock Origin以外でも搭載できた例を参考にキャプチャーを取ったので上げさせてください。
掲示板ではadguardのことが論じられていましたが、搭載の仕方はわかりかねます。
comodo ad blocker
Ad block [Plus](![スクリーンショット 2023-11-06 150857](https://github.com/tofukko/filter/assets/41463834/27c856ea-dca1-4017-8dd9-dcfe3f2b0d7b))
[](url)
![スクリーンショット 2023-11-06 151032](https://github.com/tofukko/filter/assets/41463834/9ac53305-d4a4-48e0-a552-129fbfdd8fbd)
